export const ERROR_CODES = {
  NO_TOKEN: 'NO_TOKEN',
  TOKEN_INVALID_FORMAT: 'TOKEN_INVALID_FORMAT',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  USER_DISABLED: 'USER_DISABLED',
  TOKEN_MALFORMED: 'TOKEN_MALFORMED',
  TOKEN_CREDENTIAL_INVALID: 'TOKEN_CREDENTIAL_INVALID',
  DUPLICATE_SONG: 'DUPLICATE_SONG',
  SEARCH_ERROR: 'SEARCH_ERROR',
};

export default ERROR_CODES;
